### PR TITLE
Updated README.md with links to your blogs

### PR DESCRIPTION
**Pull request by ShivaniThevar**
Added a few images and categories-wise tables. Let me know if I need to make some changes.

### CODE REVIEW

**Comment by Sudhanshu-Dubey14** [comment]
Hey @ShivaniThevar ,
Thanks for all the efforts.

A few things:
1. The link on the header is is only on .com and not on Hacksd.com, why?
1. In the first line, after the first image, please add a space after the period (.).
1. I think the definition of markdown could be improved. Please refer to [this link](https://www.markdownguide.org/getting-started/)

Lastly, can you please squash all of your commits into 1 commit?
Refer to [this link](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) for help with squashing.

Thanks again!

**Comment by ShivaniThevar** [comment]
Hey @Sudhanshu-Dubey14,

1. When I applied the link to your website to the header, it appeared blue. I felt it was not appealing and added a '.com' at the end. Please suggest an alternative.
2. Sure, will do.
3. Sure, thank you.

Yes, I will make these changes.

Regards

**Comment by Sudhanshu-Dubey14** [comment]
On of the best thing about markdown is that is supports inline HTML (and LaTex).
With HTML comes CSS which is what you can use to change the color of a specific text.
Refer to this link: https://www.tutorialspoint.com/How-to-set-font-color-in-HTML

So my suggestion is to define the entire heading in HTML and use CSS to change it's color.

**Comment by ShivaniThevar** [comment]
Okay thanks...!!

**Comment by ShivaniThevar** [comment]
Thank you... Let me know if I can help in any other way...!!

Regards

**Pull request merged**
